format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/v45/ab8992/mom6/archive/common_common/restart007/MOM.res.nc
  hashes:
    binhash: 86b346ac31ec56cb62c7145d279e9cab
    md5: ae25b3c67f242aba8bd4a046ce660c4a
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/v45/ab8992/mom6/archive/common_common/restart007/MOM.res_1.nc
  hashes:
    binhash: bc664db7c2ad77a0d4d69ad278f65f5b
    md5: 1ef7e64be2408d54e9e4a6931b5ea298
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/v45/ab8992/mom6/archive/common_common/restart007/MOM.res_2.nc
  hashes:
    binhash: f50e8e767ec06b255b7c6cb42469569b
    md5: f7f72721cbcdbf968ad28bf1709be275
work/INPUT/MOM.res_3.nc:
  fullpath: /scratch/v45/ab8992/mom6/archive/common_common/restart007/MOM.res_3.nc
  hashes:
    binhash: 4e502f5d4183afa94ded3926a5b8ea7a
    md5: 9cc49cfbe63063905273193d6901b0e2
work/INPUT/MOM.res_4.nc:
  fullpath: /scratch/v45/ab8992/mom6/archive/common_common/restart007/MOM.res_4.nc
  hashes:
    binhash: a6bfa8890633d11b043504838e9e3c9c
    md5: 7dbfe9ccdcad19644cd7c7e294065562
work/INPUT/MOM.res_5.nc:
  fullpath: /scratch/v45/ab8992/mom6/archive/common_common/restart007/MOM.res_5.nc
  hashes:
    binhash: 88a3614f298d456ffbbf87da5f5f70eb
    md5: 2df4c00b7a312782434535e80216b04b
work/INPUT/ocean_solo.res:
  fullpath: /scratch/v45/ab8992/mom6/archive/common_common/restart007/ocean_solo.res
  hashes:
    binhash: 09ef3aa8a9dc9c01fa0f49f4ae0f1472
    md5: 35beef8d941fa60d23a4aa1d412fd2ac
